name: Haskell CI

on:
  push:
    branches: [develop, main, master]
  pull_request:
    branches: [develop, main, master]
  workflow_dispatch:  # For manual triggering
  schedule:
  - cron: "3 14 15 * *"  # 14:03 on the 15th of every month (UTC)

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: ['8.8.4', '8.10.7', '9.0.2', '9.2.8', '9.4.8', '9.6.7', '9.8.4', '9.10.1', '9.12.2']
      fail-fast: false

    name: Build with GHC ${{ matrix.ghc }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Haskell setup
      uses: haskell-actions/setup@main
      with:
        ghc-version: ${{ matrix.ghc }}

    - name: Install native dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y --no-install-recommends libtcd-dev xtide-data xtide-data-nonfree

    - name: Configure
      run: |
        cabal update
        cabal configure --enable-tests --enable-benchmarks -f werror

    - name: Build dependencies
      run: cabal build --only-dependencies

    - name: Build
      run: cabal build all

    - name: Run tests
      run: |
        export HFILE_PATH=$(dpkg -L xtide-data-nonfree | grep '\.tcd$' | head -n1)
        cabal test all

    - name: Build and install xtide
      run: |
        VERSION=2.15.6
        wget -nv https://flaterco.com/files/xtide/xtide-${VERSION}.tar.xz
        tar -xf xtide-${VERSION}.tar.xz
        cd xtide-${VERSION}
        sudo apt-get install -y --no-install-recommends libpng-dev libz-dev
        ./configure --without-x
        make
        sudo make install
        sudo ldconfig /usr/local/lib

    - name: Test against xtide
      run: |
        export HFILE_PATH=$(dpkg -L xtide-data-nonfree | grep '\.tcd$' | head -n1)
        cabal exec TestTides Hinkley
